# Generated by Django 5.0.6 on 2024-06-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='User Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User EmailAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300, verbose_name='Venue Address')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Venue Zip Code')),
                ('phone', models.CharField(max_length=25, verbose_name='Contact')),
                ('web', models.URLField(verbose_name='WebPage')),
                ('email', models.EmailField(max_length=254, verbose_name='EmailAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=60, verbose_name='Event Name')),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='events.mysiteuser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
