# Generated by Django 5.0.6 on 2024-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Phone Contact'),
        ),
    ]
